version: '3.7'
services:
  tuya-mqtt:
    container_name: tuya-mqtt
    build: .
    volumes:
      - ./config:/tuya-mqtt/config
    # restart: always
    environment:
      - DEBUG=tuya-mqtt:*
    network_mode: "host"